# warp-vector-8316.rb — lightweight actor generated by PushForge Engine.
require "thread"

class Actor
  def initialize(&handler)
    @queue = Queue.new
    @handler = handler
    @thread = Thread.new do
      loop do
        msg = @queue.pop
        break if msg == :stop
        @handler.call(msg)
      end
    end
  end

  def tell(msg); @queue << msg; end
  def stop; @queue << :stop; @thread.join; end
end

if $PROGRAM_NAME == __FILE__
  a = Actor.new { |m| puts "[actor] #{m}" }
  5.times { |i| a.tell("event ##{i}") }
  a.stop
end
