// warp-vector-8316.cpp — SIMD-inspired vector primitive generated by PushForge Engine.
#include <array>
#include <cmath>
#include <iostream>

template <std::size_t N>
struct Vec {
    std::array<double, N> data{};

    Vec operator+(const Vec& other) const {
        Vec out;
        for (std::size_t i = 0; i < N; ++i) out.data[i] = data[i] + other.data[i];
        return out;
    }
    double dot(const Vec& other) const {
        double acc = 0.0;
        for (std::size_t i = 0; i < N; ++i) acc += data[i] * other.data[i];
        return acc;
    }
    double norm() const { return std::sqrt(dot(*this)); }
};

int main() {
    Vec<8> a{{1,2,3,4,5,6,7,8}};
    Vec<8> b{{8,7,6,5,4,3,2,1}};
    auto c = a + b;
    std::cout << "dot=" << a.dot(b) << " norm=" << c.norm() << "\n";
    return 0;
}
