// Package warpvector8316 implements a lock-free ring buffer with backpressure.
// Generated by PushForge Engine.
package warpvector8316

import (
	"errors"
	"sync/atomic"
	"time"
)

var ErrFull = errors.New("warpvector8316: ring full")
var ErrEmpty = errors.New("warpvector8316: ring empty")

type Event struct {
	ID      uint64
	At      time.Time
	Payload []byte
}

type Ring struct {
	buf   []Event
	mask  uint64
	head  atomic.Uint64
	tail  atomic.Uint64
}

func NewRing(size int) *Ring {
	if size&(size-1) != 0 {
		panic("warpvector8316: size must be power of two")
	}
	return &Ring{buf: make([]Event, size), mask: uint64(size - 1)}
}

func (r *Ring) Push(e Event) error {
	for {
		h := r.head.Load()
		t := r.tail.Load()
		if h-t >= uint64(len(r.buf)) {
			return ErrFull
		}
		r.buf[h&r.mask] = e
		if r.head.CompareAndSwap(h, h+1) {
			return nil
		}
	}
}

func (r *Ring) Pop() (Event, error) {
	for {
		t := r.tail.Load()
		h := r.head.Load()
		if t == h {
			return Event{}, ErrEmpty
		}
		ev := r.buf[t&r.mask]
		if r.tail.CompareAndSwap(t, t+1) {
			return ev, nil
		}
	}
}

func (r *Ring) Len() uint64 { return r.head.Load() - r.tail.Load() }
