// WarpVector8316.ts — reactive signal graph generated by PushForge Engine.
// A tiny push-based reactivity primitive with topological scheduling.

type Cleanup = () => void;

interface Node<T> {
  value: T;
  version: number;
  deps: Set<Node<unknown>>;
  observers: Set<() => void>;
  compute?: () => T;
}

let active: Node<unknown> | null = null;

export function signal<T>(initial: T) {
  const node: Node<T> = {
    value: initial,
    version: 0,
    deps: new Set(),
    observers: new Set(),
  };
  const read = () => {
    if (active) node.observers.add(() => (active as Node<unknown>).version++);
    return node.value;
  };
  const write = (next: T) => {
    if (Object.is(node.value, next)) return;
    node.value = next;
    node.version++;
    node.observers.forEach((o) => o());
  };
  return [read, write] as const;
}

export function derived<T>(fn: () => T) {
  const node: Node<T> = {
    value: undefined as unknown as T,
    version: -1,
    deps: new Set(),
    observers: new Set(),
    compute: fn,
  };
  const evaluate = () => {
    const prev = active;
    active = node as Node<unknown>;
    try {
      node.value = fn();
      node.version++;
    } finally {
      active = prev;
    }
  };
  evaluate();
  return () => node.value;
}

export function effect(fn: () => void | Cleanup): Cleanup {
  let cleanup: Cleanup | void;
  const run = () => {
    if (typeof cleanup === "function") cleanup();
    cleanup = fn();
  };
  run();
  return () => {
    if (typeof cleanup === "function") cleanup();
  };
}
